import type { CarrierQuote, QuoteRequest } from "@/lib/types"

/* ------------------------------------------------------------------ */
/*  Plain-text quote summary generators for clipboard copy.            */
/*  Output is text-message-friendly (iMessage, WhatsApp, SMS).         */
/* ------------------------------------------------------------------ */

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  })
}

function formatCoverageAmount(amount: number): string {
  return `$${amount.toLocaleString("en-US")}`
}

function roundedMonthly(premium: number): string {
  return `$${Math.round(premium)}`
}

/** First name + last initial for privacy in text messages. */
function privacyName(fullName: string): string {
  const parts = fullName.trim().split(/\s+/)
  const first = parts[0] ?? ""
  const lastInitial = parts.length > 1 ? ` ${parts[parts.length - 1]![0]}.` : ""
  return `${first}${lastInitial}`
}

/** Pick the single most useful feature for a carrier line item. */
export function pickKeyFeature(quote: CarrierQuote): string {
  const { carrier, features } = quote

  // Prioritize tobacco key note if it exists (unique differentiator)
  if (carrier.tobacco.keyNote) return carrier.tobacco.keyNote

  // Living benefits are a strong selling point
  if (carrier.livingBenefits && carrier.livingBenefits !== "None specified") {
    return "Living benefits included"
  }

  // State availability
  if (carrier.statesNotAvailable.length === 0) {
    return "All states"
  }

  // Fall back to first feature
  return features[0] ?? carrier.amBestLabel
}

/**
 * Generate a full quote summary with top carriers.
 * Designed for text messages — plain text, no markdown.
 */
export function buildQuoteSummary(
  intake: QuoteRequest,
  topCarriers: CarrierQuote[],
): string {
  const name = privacyName(intake.name)
  const carriers = topCarriers.slice(0, 3)

  const lines: string[] = [
    "Life Insurance Quote Summary",
    "\u2501".repeat(23),
    "",
    `Client: ${name}, ${intake.age} ${intake.gender}`,
    `Coverage: ${formatCoverageAmount(intake.coverageAmount)} \u00B7 ${intake.termLength}-Year Term`,
    `State: ${intake.state}`,
  ]

  if (intake.tobaccoStatus === "smoker") {
    lines.push("Tobacco rates applied")
  }
  if (intake.medicalConditions && intake.medicalConditions.length > 0) {
    lines.push("Medical conditions considered")
  }

  lines.push("")
  lines.push("Top Options:")
  lines.push("")

  for (let i = 0; i < carriers.length; i++) {
    const q = carriers[i]!
    const feature = pickKeyFeature(q)
    lines.push(`${i + 1}. ${q.carrier.name} \u2014 ${roundedMonthly(q.monthlyPremium)}/mo`)
    lines.push(`   AM Best: ${q.carrier.amBest} \u00B7 ${feature}`)
    if (i < carriers.length - 1) lines.push("")
  }

  lines.push("")
  lines.push("\u2501".repeat(23))
  lines.push(`Generated by Ensurance \u00B7 ${formatDate()}`)

  return lines.join("\n")
}

/**
 * Generate a single-carrier summary for the detail modal.
 * Shorter format for sharing a specific recommendation.
 */
export function buildSingleCarrierSummary(
  quote: CarrierQuote,
  coverageAmount: number,
  termLength: number,
): string {
  return [
    `${quote.carrier.name} \u2014 ${roundedMonthly(quote.monthlyPremium)}/mo for ${formatCoverageAmount(coverageAmount)} ${termLength}-year term`,
    `AM Best: ${quote.carrier.amBest}`,
    `Generated by Ensurance`,
  ].join("\n")
}
